In [7]:
import numpy as np
#np.random.rand (uniform distribution)
x=np.random.rand(4)
print("random numbers:")
print(x)
y=np.random.rand(2,2) #(rows,columns)
print(y)


random numbers:
[0.95660223 0.82762908 0.6915541  0.47579577]
[[0.75686662 0.71025953]
 [0.18856539 0.75304518]]


In [10]:
#np.random.randn() (standard normal distribution)
a = np.random.randn(5)
print("Random numbers:")
print(a)
p=np.random.randn(2,3)
print(p)

Random numbers:
[-0.30731435 -1.0802826  -1.52418632 -0.49260355 -0.44100547]
[[ 1.44093256 -0.01270185 -2.23338065]
 [ 0.08550555  0.85132193  0.01802606]]


In [14]:
#np.random.randint() (random integers)
a = np.random.randint(1,10,5)  #(low,hign,size) 
#high is not included
print("Random integers:",a)
b = np.random.randint(1,100,(2, 3))
print(b)

Random integers: [2 2 7 9 9]
[[37 76 36]
 [18 48 15]]


In [16]:
#np.random.normal()
#np.random.normal(mean, standard_deviation, size)
v=np.random.normal(50,10,5)
print(v)
h=np.random.normal(50,10,(2,3))
print(h)

[55.27711018 69.95218891 41.94099039 55.19972212 36.30609406]
[[46.2112801  54.42739885 45.50048277]
 [55.18348425 44.95028369 50.28302501]]


In [20]:
#computing statistics
s=np.random.normal(30,40,10)
print("data:",s)
print("mean:",np.mean(s))
print("median:",np.median(s))
print("standard devision:",np.std(s))
print("minimum:",np.min(s))
print("maximum",np.max(s))

data: [64.01274085 58.74131039 95.52627105 14.06093819  5.11364283 66.09305243
 26.02180991 32.8212143   6.38148493 73.27480785]
mean: 44.20472727196571
median: 45.781262341119216
standard devision: 29.814929624672818
minimum: 5.113642829892683
maximum 95.52627105317418
