In [18]:
#1D array using np.array
import numpy as np
arr_1=np.array([10,20,30,40,50])
print("1D array:")
print(arr_1)
arr_2=np.arange(1,20)
print("\narray :")
print(arr_2)

#linespacing
arr_3=np.linspace(1,5,5)
print(arr_3)

#indexing
print("second element of arr_1:",arr_1[1])
print("last element of the arr_2:",arr_2[-1])

#slicing
print("first 5 elements in arr_2:",arr_2[0:5])
print(arr_2[:9:2])
print("reverse of arr_1:",arr_1[: :-1])

#reshaping
arr_4=np.array([1,2,3,4,5,6,7,8,9,1])
reshaped=np.reshape(arr_4,(2,5))
print(reshaped)

#mathematical functions
arr1=([3,4,5,6,7])
arr2=([4,5,6,3,4])
print("sum=",np.sum(arr1))
print("mean of arr2:",np.mean(arr2))
print("exponential:",np.exp(arr1))
    

1D array:
[10 20 30 40 50]

array :
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1. 2. 3. 4. 5.]
second element of arr_1: 20
last element of the arr_2: 19
first 5 elements in arr_2: [1 2 3 4 5]
[1 3 5 7 9]
reverse of arr_1: [50 40 30 20 10]
[[1 2 3 4 5]
 [6 7 8 9 1]]
sum= 25
mean of arr2: 4.4
exponential: [  20.08553692   54.59815003  148.4131591   403.42879349 1096.63315843]


In [43]:
#2D array using np.array
import numpy as np
arr3=np.array([[1,2,3],
       [3,4,5],
       [4,5,6]])
print("2D array:")
print(arr3)
print(arr3[0,0])
print(arr3[1,2])
print(arr3[0:2,0:2])
print("second row:",arr3[1, :])
print("first column:",arr3[:, 1])
arr4=np.array([[3,3,3],
     [4,5,6],
     [6,4,2]])
print("sum:\n",arr3+arr4)
print("subtraction:\n",arr3-arr4)
print("multiplecation:\n",arr3*arr4)
print(np.sum(arr3))
#sum of a specific row and column
print("sum of first row:")
print(np.sum(arr3,axis=0))
print(np.mean(arr3))
print(np.mean(arr3, axis=1))
print(np.reshape(arr3,(1, 9)))
      

2D array:
[[1 2 3]
 [3 4 5]
 [4 5 6]]
1
5
[[1 2]
 [3 4]]
second row: [3 4 5]
first column: [2 4 5]
sum:
 [[ 4  5  6]
 [ 7  9 11]
 [10  9  8]]
subtraction:
 [[-2 -1  0]
 [-1 -1 -1]
 [-2  1  4]]
multiplecation:
 [[ 3  6  9]
 [12 20 30]
 [24 20 12]]
33
sum of first row:
[ 8 11 14]
3.6666666666666665
[2. 4. 5.]
[[1 2 3 3 4 5 4 5 6]]
