In [10]:
#vectorized operations
import numpy as np
s=np.array([2,3,4,5])
p=np.array([11,22,33,55])
#addition
result=np.add(s,p)
print(result)
#np.sqrt
r=np.array([1,4,9,16,25])
print("sqrt=",np.sqrt(r))
#np.exp()
u=np.array([2,3,4,6,7])
print(np.exp(u))

#broadcasting
t=np.array([5,6,7,3,4,23])
print(t+5)
h=np.array([6,7,8,9,10])
v=np.array([[2,3,4,5,6],
      [4,5,6,4,6]])
print(h+v)

i = np.array([[1],
              [2],
              [3]])
m = np.array([10, 20, 30])
print(i + m)

[13 25 37 60]
sqrt= [1. 2. 3. 4. 5.]
[   7.3890561    20.08553692   54.59815003  403.42879349 1096.63315843]
[10 11 12  8  9 28]
[[ 8 10 12 14 16]
 [10 12 14 13 16]]
[[11 21 31]
 [12 22 32]
 [13 23 33]]
